version: "3"
services:
  app:
    build: .
    ports:
      - 81:80
    volumes:
      - ./html:/var/www/html
    container_name: sample_system

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - sampleSystem:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sample_system
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test

volumes:
  sampleSystem:
